//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrusadersService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrusadersEntities : DbContext
    {
        public CrusadersEntities()
            : base("name=CrusadersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Games1> Games1 { get; set; }
        public DbSet<GamesResult> GamesResults { get; set; }
        public DbSet<Players1> Players1 { get; set; }
        public DbSet<Ticket> Tickets { get; set; }
    }
}
