//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrusadersService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players1
    {
        public Players1()
        {
            this.Games1 = new HashSet<Games1>();
        }
    
        public int id { get; set; }
        public string Number { get; set; }
        public string FamilyName { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
    
        public virtual ICollection<Games1> Games1 { get; set; }
    }
}
